# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-17 06:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_auto_20170414_1408'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodExperience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(blank=True, db_column='YEAR', max_length=10, null=True)),
                ('area', models.CharField(blank=True, db_column='AREA', max_length=20, null=True)),
                ('engn_nm', models.CharField(blank=True, db_column='ENGN_NM', max_length=20, null=True)),
                ('cttpc', models.CharField(blank=True, db_column='CTTPC', max_length=20, null=True)),
                ('adres', models.CharField(blank=True, db_column='ADRES', max_length=50, null=True)),
                ('rdnamdr', models.CharField(blank=True, db_column='RDNAMDR', max_length=50, null=True)),
                ('nw_zip', models.CharField(blank=True, db_column='NW_ZIP', max_length=10, null=True)),
                ('la', models.CharField(blank=True, db_column='LA', max_length=20, null=True)),
                ('lo', models.CharField(blank=True, db_column='LO', max_length=20, null=True)),
            ],
            options={
                'db_table': 'food_experience',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=10, null=True)),
                ('password', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'info',
                'managed': False,
            },
        ),
    ]
