# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-21 11:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.SmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FoodExperience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(blank=True, db_column='YEAR', max_length=10, null=True)),
                ('area', models.CharField(blank=True, db_column='AREA', max_length=20, null=True)),
                ('engn_nm', models.CharField(blank=True, db_column='ENGN_NM', max_length=20, null=True)),
                ('cttpc', models.CharField(blank=True, db_column='CTTPC', max_length=20, null=True)),
                ('adres', models.CharField(blank=True, db_column='ADRES', max_length=50, null=True)),
                ('rdnamdr', models.CharField(blank=True, db_column='RDNAMDR', max_length=50, null=True)),
                ('nw_zip', models.CharField(blank=True, db_column='NW_ZIP', max_length=10, null=True)),
                ('la', models.CharField(blank=True, db_column='LA', max_length=20, null=True)),
                ('lo', models.CharField(blank=True, db_column='LO', max_length=20, null=True)),
            ],
            options={
                'db_table': 'food_experience',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FoodGood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bssh_nma', models.CharField(blank=True, db_column='BSSH_NMA', max_length=50, null=True)),
                ('telno', models.CharField(blank=True, db_column='TELNO', max_length=20, null=True)),
                ('addr', models.CharField(blank=True, db_column='ADDR', max_length=100, null=True)),
                ('main_menu', models.CharField(blank=True, db_column='MAIN_MENU', max_length=50, null=True)),
            ],
            options={
                'db_table': 'food_good',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FoodRecipeBasic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_id', models.CharField(blank=True, db_column='RECIPE_ID', max_length=50, null=True)),
                ('recipe_nm_ko', models.CharField(blank=True, db_column='RECIPE_NM_KO', max_length=50, null=True)),
                ('sumry', models.CharField(blank=True, db_column='SUMRY', max_length=100, null=True)),
                ('nation_code', models.CharField(blank=True, db_column='NATION_CODE', max_length=20, null=True)),
                ('nation_nm', models.CharField(blank=True, db_column='NATION_NM', max_length=20, null=True)),
                ('ty_code', models.CharField(blank=True, db_column='TY_CODE', max_length=20, null=True)),
                ('ty_nm', models.CharField(blank=True, db_column='TY_NM', max_length=20, null=True)),
                ('cooking_time', models.CharField(blank=True, db_column='COOKING_TIME', max_length=50, null=True)),
                ('calorie', models.CharField(blank=True, db_column='CALORIE', max_length=50, null=True)),
                ('qnt', models.CharField(blank=True, db_column='QNT', max_length=50, null=True)),
                ('level_nm', models.CharField(blank=True, db_column='LEVEL_NM', max_length=20, null=True)),
                ('irdnt_code', models.CharField(blank=True, db_column='IRDNT_CODE', max_length=100, null=True)),
                ('pc_nm', models.CharField(blank=True, db_column='PC_NM', max_length=100, null=True)),
            ],
            options={
                'db_table': 'food_recipe_basic',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=10, null=True)),
                ('password', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'info',
                'managed': False,
            },
        ),
    ]
