# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-22 17:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodMasters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(blank=True, db_column='YEAR', max_length=20, null=True)),
                ('ordr', models.CharField(blank=True, db_column='ORDR', max_length=20, null=True)),
                ('asign', models.CharField(blank=True, db_column='ASIGN', max_length=20, null=True)),
                ('nm', models.CharField(blank=True, db_column='NM', max_length=20, null=True)),
                ('hold_skill', models.CharField(blank=True, db_column='HOLD_SKILL', max_length=20, null=True)),
                ('apntdt', models.CharField(blank=True, db_column='APNTDT', max_length=20, null=True)),
            ],
            options={
                'db_table': 'food_masters',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FoodRecipeSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_id', models.CharField(blank=True, db_column='RECIPE_ID', max_length=20, null=True)),
                ('irdnt_sn', models.CharField(blank=True, db_column='IRDNT_SN', max_length=20, null=True)),
                ('irdnt_nm', models.CharField(blank=True, db_column='IRDNT_NM', max_length=20, null=True)),
                ('irdnt_cpcty', models.CharField(blank=True, db_column='IRDNT_CPCTY', max_length=20, null=True)),
                ('irdnt_ty_code', models.CharField(blank=True, db_column='IRDNT_TY_CODE', max_length=20, null=True)),
                ('irdnt_ty_nm', models.CharField(blank=True, db_column='IRDNT_TY_NM', max_length=20, null=True)),
            ],
            options={
                'db_table': 'food_recipe_source',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FoodRecipeStep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_id', models.CharField(blank=True, db_column='RECIPE_ID', max_length=10, null=True)),
                ('cooking_no', models.CharField(blank=True, db_column='COOKING_NO', max_length=10, null=True)),
                ('cooking_dc', models.CharField(blank=True, db_column='COOKING_DC', max_length=255, null=True)),
                ('stre_step_image_url', models.CharField(blank=True, db_column='STRE_STEP_IMAGE_URL', max_length=255, null=True)),
                ('step_tip', models.CharField(blank=True, db_column='STEP_TIP', max_length=255, null=True)),
            ],
            options={
                'db_table': 'food_recipe_step',
                'managed': False,
            },
        ),
    ]
